name: Validate Token Lists

on:
  push:
    branches: [main]
    paths:
      - 'assets/**/*.json'
  pull_request:
    branches: [main]
    paths:
      - 'assets/**/*.json'
  workflow_dispatch:  # Allow manual triggering

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate token lists
        run: npm run validate
      
      - name: Run tests
        run: npm run test
      
      - name: Check for formatting issues
        run: |
          # Check if all JSON files are formatted with 2-space indentation
          find assets -name "*.json" -type f -exec grep -L '  "tokens":' {} \; > unformatted.txt
          if [ -s unformatted.txt ]; then
            echo "The following files don't have 2-space indentation:"
            cat unformatted.txt
            exit 1
          fi 